### ISSUE TITLE
Uncaught TypeError: '[object Uint8Array]' is not a valid argument for 'Function.prototype.apply' in PhantomJS

### ISSUE THREAD

**Issue by humphd** [imaya/zlib.js#33]
Using `bin/unzip.min.js` in PhantomJS, I get:

```
Uncaught TypeError: '[object Uint8Array]' is not a valid argument for 'Function.prototype.apply' (evaluating 'a.slice(b,b+=this.h)') (file:///Users/dave/Sites/repos/filer/lib/unzip.js:24)
```

It is this pattern: https://github.com/imaya/zlib.js/blob/master/src/unzip.js#L203-L205

``` javascript
String.fromCharCode.apply(null, USE_TYPEDARRAY ?
    input.subarray(ip, ip += this.fileNameLength) :
    input.slice(ip, ip += this.fileNameLength)
);
```

The pdf.js guys had a similar issue, see https://github.com/mozilla/pdf.js/issues/1820.  It's a bug in old Chrome/WebKits.

**Comment by imaya** [comment]
I do not fix this problem, I think it should be fixed by PhantomJS.
And,
It seems to have been fixed in PhantomJS 2.0
