### ISSUE TITLE
Gzip Lib have problems.

### ISSUE THREAD

**Issue by LuoZijun** [imaya/zlib.js#37]
# CODE

``` HTML
<script src="gzip.min.js" type="text/javascript"></script>
<script src="gunzip.min.js"  type="text/javascript"></script>

<script type="text/javascript">
    // Gzip
    var plain = "hello";

    console.log('Input String: ' + plain);
    // plain = Array.<number> or Uint8Array
    var gzip = new Zlib.Gzip(plain);
    var compressed = gzip.compress();
    console.log(compressed);

    // compressed = Array.<number> or Uint8Array
    var gunzip = new Zlib.Gunzip(compressed);
    var plain = gunzip.decompress();
    console.log(plain);
</script>
```
# OUTPUT

>   Note: Run This JavaScript In Google Chrome Brower(Ver:35.0.1916.153).

```
    Input String: hello zlib.html:20
    [31, 139, 8, 0, 37, 38, 173, 83, 0, 255, 13, 192, 129, 0, 0, 0, 0, 0, 144, 255, 107, 4, 29, 247, 34, 198, 5, 0, 0, 0] zlib.html:24
    Uncaught Error: invalid CRC-32 checksum: 0xff41d912 / 0xc622f71d gunzip.min.js:25
```
#9 Does CRC-32 lib have problems?

**Comment by wildcatgerry** [comment]
Please use the function from the README.md to convert a string to array

    function stringToByteArray(str) {
        var array = new (window.Uint8Array !== void 0 ? Uint8Array : Array)(str.length);
        var i;
        var il;

        for (i = 0, il = str.length; i < il; ++i) {
            array[i] = str.charCodeAt(i) & 0xff;
        }

        return array;
    }
    // Gzip
    var plain = stringToByteArray("hello");
