### ISSUE TITLE
Infinite loop when decoding invalid zip file

### ISSUE THREAD

**Issue by evanw** [imaya/zlib.js#45]
I ran across this while debugging something:

```
var Zlib = require('./bin/node-zlib');
var data = new Buffer([
  0x08, 0x1D, 0x74, 0x65, 0x73, 0x74, 0x2f, 0x61,
  0x2f, 0x62, 0x6c, 0x61, 0x68, 0x2e, 0x6a, 0x73,
  0x55, 0x58, 0x0c, 0x00, 0x14, 0x2c, 0xdb, 0x55,
  0xa9, 0x98, 0x85, 0x55, 0xf5, 0x01, 0x14, 0x00,
  0x2b, 0x4b, 0x2c, 0x52, 0x28, 0x4e, 0x2d, 0x2a,
  0x4b, 0x2d, 0x52, 0xb0, 0x55, 0xc8, 0x28, 0x29,
  0x29, 0xd0, 0x4b,
]);
console.log(Zlib.inflateSync(data));
```

It looks like a hang in `decodeHuffmanAdaptive`. This bug is especially unfortunate because it's been ported to other implementations that are based on this library (https://github.com/brendan-duncan/archive for example).

**Comment by imaya** [comment]
Thank you for bug report.
This bug is fixed in 4971111c1ad49e3c353ed38d51850e1ff5c206b9 and 958522ed7c75650798d0dbe8b0eaef362fda86c6.
It will be included in the next release.
