### ISSUE TITLE
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead

### ISSUE THREAD

**Issue by gracemi** [imaya/zlib.js#46]
As the tittle says, "//@" must be change in all *.min.js libraries.
![captura de pantalla de 2015-10-23 08 47 27](https://cloud.githubusercontent.com/assets/12226128/10686281/cdddb0d6-7962-11e5-8afb-d9ab942b403d.png)
Firefox 41.0.2

**Comment by hallvors** [comment]
Same as #23 :)
