### ISSUE TITLE
zlib.js - Uncaught Error: invalid CRC-32 checksum

### ISSUE THREAD

**Issue by csdivi** [imaya/zlib.js#8]
I am exploring the gzip library, I am getting 'Uncaught Error: invalid CRC-32 checksum' error with my sample code. Please see the code and error below.
Please help me to resolve this issue.

   var zipper = new Zlib.Gzip("Try to compress this string....");
   var compressed = zipper.compress();
   var uncompressed = new Zlib.Gunzip(compressed);
   var original = uncompressed.decompress();
   console.log(original);

Uncaught Error: invalid CRC-32 checksum: 0x43eb5 / 0x6909acb0

**Comment by samikrc** [comment]
I am facing the same problem. Not sure I understand how you describe it as resolved in your second post. Do you mean that we need to convert a string to an UInt8Array before compressing it?
